#!/usr/bin/env bash
# we get primary version from `VERSION` file
set -e
export APP=${1:?"app name is required"}
export VERSION=${2:?"version is required"}
BUILD_DIR=./build

rm -f "$BUILD_DIR/$APP"
mkdir -p "$BUILD_DIR"
# install only the binary
# this prevents go from looking at test-only directory
go build -ldflags "-X main.version=${VERSION}"  -x -v -o $BUILD_DIR/$APP github.com/zerobotlabs/relax
