#!/usr/bin/env bash
# we get primary version from `VERSION` file
set -e
export APP=${1:?"app name is required"}
export VERSION=${2:?"version is required"}
BUILD_DIR=./build

rm -f "$BUILD_DIR/$APP"
mkdir -p "$BUILD_DIR"
# install only the binary
# this prevents go from looking at test-only directory
VERSION=$VERSION godep go install -x -ldflags "-X main.version ${VERSION}"
BUILD_DIR=$BUILD_DIR bash -c 'cp $GOBIN/$APP $BUILD_DIR/$APP'
