#!/bin/bash

export EQUINOX_APP_ID=app_6dd9kcb4hZ1

if [ -z "$EQUINOX_BETA" ]; then
  VERSION=$(cat VERSION)
  CHANNEL=stable
else
  VERSION=$(git rev-parse --short HEAD)
  CHANNEL=beta
fi

echo "Installing $VERSION to $CHANNEL with EQUINOX_SIGNING_KEY_FILE"
/usr/local/bin/equinox release \
--version=$VERSION \
--channel=$CHANNEL \
--platforms="darwin_amd64 linux_amd64" \
--signing-key=$EQUINOX_SIGNING_KEY_FILE \
--app=$EQUINOX_APP_ID \
--token=$EQUINOX_CREDENTIAL \
github.com/zerobotlabs/relax
